### ISSUE TITLE
AutoRaise

### ISSUE THREAD

**Issue by PrincipeAzzurro** [synappser/synappser.github.io#1]
Thank you for this brilliant idea - I'd ℓσνє to test this out, unfortunately on your website there is no "installer" or .dmg for AutoRaise, and the command line method mentioned here on GitHub for it gives me repeated error codes. Could you help out? THANK YOU!

**Comment by synappser** [comment]
Hi @PrincipeAzzurro,

I'll be honest, I am stretched thin these days with the launch of FinderFix. I promise I'll do my best to push AutoRaise out of private beta as soon as possible.

It's not just a teaser and I am sure you're going to love it. It's a compelling innovation to the traditional focus-follow-mouse functionality. A focus-follows-mouse on steroids!

Stay tuned!

**Comment by synappser** [comment]
@PrincipeAzzurro,

If you want to take a sneak peek at AutoRaise's **focus-follows-mouse** implementation, I just added [a video demoing its "extending the Desktop" feature](https://synappser.github.io/apps/autoraise/).

**Comment by synappser** [comment]
Your wish has been granted! I opened [**AutoRaise**](https://synappser.github.io/apps/autoraise/) to public beta today. It is available on Synapper's [Downloads](https://synappser.github.io/downloads/) page.
