### ISSUE TITLE
How to turn on autofocus

### ISSUE THREAD

**Issue by RaySimmons** [synappser/synappser.github.io#3]
Can you tell me how to turn this on? I installed it (and granted access), but nothing is different. Thanks.

**Comment by synappser** [comment]
Hi Ray,

Do you mind giving me more details such as your operating system version, the steps you followed, etc. By granted access, you do mean Accessibility in the Privacy settings, isn't it? A screenshot of your AutoFocus settings (the preferences window) would be great. I would also like you to open an issue on the appropriate repo (i.e. https://github.com/synappser/AutoFocus/issues).

Thanks

**Comment by RaySimmons** [comment]
Thank you. I posted on Github. Let me know where I’m off track here. Best, Ray

[cid:6EC14D8B-A8ED-42B3-B978-3AB6D9B5D23A]

[cid:4E3A0DD6-08D5-4917-A062-319F9626C18C]


[cid:580F245B-13F4-4163-BD90-5BB1EB1ADC6E]

[cid:A01A6826-69B4-46EC-B32F-01081038D9E8]

On Dec 9, 2022, at 10:23 PM, synappser ***@***.******@***.***>> wrote:



Hi Ray,

Do you mind giving me more details such as your operating system version, the steps you followed, etc. By granted access, you do mean Accessibility in the Privacy settings, isn't it? A screenshot of your AutoFocus settings (the preferences window) would be great. I would also like you to open an issue on the appropriate repo (i.e. https://github.com/synappser/AutoFocus/issues).

Thanks

**Comment by synappser** [comment]
Issue moved to https://github.com/synappser/AutoFocus/issues.
